name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build --stacktrace
